In [1]:
# Import NumPy package to load its functions (np is conventional abbreviation to use in the code)
import numpy as np

In [ ]:
# Initializing NumPy arrays with lists
a = np.array([1, 2, 3, 4])		# (1D) vector array (lowercase name)
A = np.array([[2, 3],   		# (2D) matrix array (uppercase name)
              [4, 5]])

# Initializing NumPy arrays with numbers
b = np.arange(5)		        # vector from 0 to 4
c = np.arange(10, 15)	        # vector from 10 to 14
d = np.arange(15, 50, 10)	    # vector from 15 to 49, with steps of 10
e = np.linspace(0, 100, 5)	    # vector 5 number values between 0 and 100
f = np.empty(2)		            # vector declaration that needs to be initialized
B = np.zeros((2, 3, 4))	        # matrix 2x3x4 (3D) matrix with zeros
C = np.ones((1, 2))		        # matrix 1x2 (2D) matrix with ones
X = np.random.rand(5, 5)	    # matrix 5x5 (2D) with random values <0, 1)
Y = np.random.randn(100, 36, 36)# matrix 50x36x36 (3D) with random numbers from normal distribution

In [ ]:
print("a =", a); print("A:\n", A); print("b =", b); print("c =", c); print("d =", d); print("e =", e); 
print("f =", f); print("B:\n", B); print("C:\n", C); print("X:\n", X); print("Y:\n", Y)

In [ ]:
# Displaying properties of NumPy arrays (shape, ndim, size)
B = np.zeros((2, 3, 4))
B_shape = B.shape   # length of each dimensions - shape of array
B_ndim = B.ndim    	# amount of array dimensions
B_size = B.size    	# amount of values in array

In [ ]:
print("B_shape =", B_shape); print("B_ndim =", B_ndim); print("B_size =", B_size)

In [ ]:
# Transforming functions of NumPy arrays (transpose, reshape)
Y = np.random.randn(2, 2, 3)
Y_transposed = np.transpose(Y)          # transposes Y - reverses the axes of an array
Y_transposed = Y.transpose()            # does the same, anytime we use np. with matrix parameters, it can also call it from the first matrix passed
Y_reshaped = np.reshape(Y, (2, 2 * 3))  # reshapes dimensions from 2x3x2 matrix to 2x6 
Y_reshaped = Y.reshape(-1, 2 * 3)       # does the same, -1 lets NumPy calculate the shape length based on the remaining number of elements

In [ ]:
print("Y.shape =", Y.shape); print("Y:\n", Y); print("Y_transposed.shape", Y_transposed.shape); print("Y_transposed:\n", Y_transposed); 
print("Y_reshaped.shape", Y_reshaped.shape); print("Y_reshaped:\n", Y_reshaped)

In [ ]:
# Computing functions over axises in NumPy arrays (sum/mean/exp etc.)
X = np.array([[1, 3, 5, 7],
              [6, 7, 3, 1],
              [1, 4, 5, 1]])
X_sum = np.sum(X, axis=0)	    # sum out of elements inside of 1. array: (1,6,1)(3,7,4)(5,3,5)(7,1,1) [columns]

Z = np.array([[[2, 4, 6],
               [1, 2, 3]],

              [[4, 6, 8],
               [7, 8, 9]]])
Z_mean_0 = np.mean(Z, axis=0)	# compute means out of elements inside of 1. array - 1. row uses: (2,4)(4,6)(6,8)  [1on1 outside]
Z_mean_1 = np.mean(Z, axis=1)	# compute means out of elements inside of 2. array - 1. row uses: (2,1)(4,2),(6,3) [columns]
Z_mean_2 = Z.mean(axis=2)	    # compute means out of elements inside of 3. array - 1. row uses: (2,4,6)(1,2,3)   [rows]

In [ ]:
print("X_sum", X_sum); print("Z_mean_0:\n", Z_mean_0)
print("Z_mean_1:\n", Z_mean_1); print("Z_mean_2:\n", Z_mean_2)

In [11]:
# Arithmetic element wise operations with vectors
a1 = np.array([9, 8, 7, 6])
a2 = np.array([1, 2, 3, 4])
a_added = a1 + a2   # adding (np.add - has more parameters for adding)
a_subtr = a1 - a2   # subtracting (np.subtract)
a_multi = a1 * a2   # multiplication (np.multiply)
a_divid = a1 / a2   # division (np.divide)

# Vectorization with np. vs Python loops)
# ELEMENT WISE MULTIPLICATION
a_multi = np.multiply(a1,a2)    # [9*1, 8*2, 7*3, 8*4]
a_multi = np.zeros(len(a1))
for i in range(len(a1)):
    a_multi[i] = a1[i] * a2[i]

# DOT PRODUCT
a_dot = np.dot(a1,a2)	        # 9*1 + 8*2 + 7*3 + 6*4
a_dot = 0
for i in range(len(a1)):
    a_dot += a1[i] * a2[i]

# OUTER PRODUCT
a_outer = np.outer(a1,a2)	    # [[9*1, 9*2, 9*3, 9*4], [8*1, 8*2 …], … ]
a_outer = np.zeros((len(a1),len(a2)))
for i in range(len(a1)):
    for j in range(len(a2)):
        a_outer[i,j] = a1[i] * a2[j]


In [12]:
print("a_added =", a_added); print("a_subtr =", a_subtr); print("a_multi =", a_multi); print("a_divid =", a_divid);
print("a_multi =", a_multi); print("a_dot =", a_dot); print("a_outer:\n", a_outer)

a_added = [10 10 10 10]
a_subtr = [8 6 4 2]
a_multi = [ 9. 16. 21. 24.]
a_divid = [9.         4.         2.33333333 1.5       ]
a_multi = [ 9. 16. 21. 24.]
a_dot = 70
a_outer:
 [[ 9. 18. 27. 36.]
 [ 8. 16. 24. 32.]
 [ 7. 14. 21. 28.]
 [ 6. 12. 18. 24.]]


In [15]:
# Arithmetic operations with matrix and vector (multiplication and dot product)
a1 = np.array([1, 2, 3, 4])
A1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])

Aa_multi = np.multiply(A1, a1)  # [[1*1, 2*2, 3*3, 4*4], [1*5, 1*6, 1*7, 1*8]]
Aa_dot = np.dot(A1, a1)         # [1*1 + 2*2 + 3*3 + 4*4, 5*1 + 6*2 + 7*3 + 8*4]
Aa_dot = np.zeros(A1.shape[0])
for i in range(len(A1)):
    for j in range(len(a1)):
        Aa_dot[i] += A1[i,j] * a1[j]

# Arithmetic operations with matrices (multiplication and dot product)
A2 = np.array([[4, 6],
               [3, 5],
               [2, 4],
               [1, 3]])
A11_multi = np.multiply(A1, A2.T)   # we need to transpose A2 to match the array shapes 
                                    # [[1*4, 2*3, 3*2, 4*1], [5*6, 6*5, 7*4, 8*3]]
A12_dot = np.dot(A1, A2)            # multiplying AxB * BxC shaped matrices (4x3 * 3x1) 
                                    # [[1*4 + 2*3 + 3*2 + 4*1, 1*6 + 2*5 + 3*4 + 4*3],
                                    #  [5*4 + 6*3 + 7*2 + 8*1, 5*6 + 6*5 + 7*4 + 8*3]]

In [16]:
print("Aa_multi:\n", Aa_multi); print("Aa_dot =", Aa_dot); 
print("A11_multi:\n", A11_multi); print("A12_dot:\n", A12_dot)

Aa_multi:
 [[ 1  4  9 16]
 [ 5 12 21 32]]
Aa_dot = [30. 70.]
A11_multi:
 [[ 4  6  6  4]
 [30 30 28 24]]
A12_dot:
 [[ 20  40]
 [ 60 112]]


In [13]:
# np.dot alternatives: @ and np.matmul in which the differences are:
# 1: Multiplication by scalars is not allowed -> use *
# 2: Stacks of matrices are broadcast together as if the matrices were elements.
#    (acts differently when we're dealing with 3D or higher dim. matrices)
# difference between matmul and @: matmul has additional parameters and works with lists
# https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication
# https://mkang32.github.io/python/2020/08/30/numpy-matmul.html

# dot vs @ example. Dot uses [2, 4] vector with all vectors, whereas @ multiplies them only with the corresponding matrix
a_3D = np.array([[[2, 4],
                  [1, 2]],
                 [[4, 6],
                  [7, 8]]])
b_3D = np.array([[[2, 4],
                  [1, 2]],
                 [[4, 6],
                  [7, 8]]])
                        # blue (2.) array is multiplied by all blue arrays in the b
ab_dot = np.dot(a, b)   # [[[[2*2 + 4*1, 2*4 + 4*2], [2*4 + 4*7, 2*6 + 4*8]], [1*2 + 2*1, 1*4 + 2*2] ...
ab_at = a @ b           # [[[2*2 + 4*1, 2*4 + 4*2], [1*2 + 2*1, 1*4 + 2*2]], [4*4 + 6*7, 4*6 + 6*8], [7*4 + 8*7, 7*6 + 8*8]]


In [14]:
print("ab_dot:\n", ab_dot); print("ab_at:\n", ab_at)

ab_dot:
 [[[[  8  16]
   [ 36  44]]

  [[  4   8]
   [ 18  22]]]


 [[[ 14  28]
   [ 58  72]]

  [[ 22  44]
   [ 84 106]]]]
ab_at:
 [[[  8  16]
  [  4   8]]

 [[ 58  72]
  [ 84 106]]]


In [ ]:
# Index referencing (getting element or sublist of elements from the array)
a = np.array([1, 2, 3, 4, 5])
one = a[0]          # gets the 1. element from the vector
three = a[2]        # gets the 3. element from the vector

A = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
row_0 = A[0]        # gets 1. row from 2D matrix
eight = A[2][1]     # gets number 8 from 2D matrix
eight = A[2, 1]     # does the same

idx = [0, 2]        # saving vector as index reference in a variable
A_idxed = A[idx]    # gets first and last row from 2D matrix

# Slicing
a_sub = a[1:4]       # gets all elements except for the first and last one
a_sub = a[1:-1]      # does the same, -1 is the last element
A_sub = A[0:2]       # gets first two rows from 2D matrix
A_sub = A[:2]        # does the same
A_sub_rows = A[1:4]  # gets last two rows
A_sub_cols = A[:, 1] # gets all rows' second element

B = np.array([[[1,2,3], [2,3,4], [4,5,6]],
              [[2,3,4], [6,5,4], [4,3,2]]])
B_sub_step = B[::, ::, ::2] # gets first and last element in the vectors

In [ ]:
print("one =", one); print("three =", three); print("row_0 =", row_0); print("eight =", eight)
print("a_sub =", a_sub); print("A_sub:\n", A_sub); print("A_sub_rows:\n", A_sub_rows); print("A_sub_cols =", A_sub_cols)
print("B_sub_step:\n", B_sub_step)

In [ ]:
# Copying and Broadcasting (treating arrays with different shapes during arithmetic operations)
X1 = np.array([[2, 3, 4],
               [3, 5, 8],
               [9, 8, 0]])
X2 = np.copy(X1)
X2[:] = 1   # sets all values to 1

X3 = X2.copy()
X3[0] = 0   # sets all values in the first row to 0

X4 = X3 * 2 # multipling matrix with a scalar (Python list would just duplicate the values)

In [ ]:
print("X1:\n", X1); print("X2:\n", X2); print("X3:\n", X3); print("X4:\n", X4)

In [ ]:
# Types and conversions
A1 = np.zeros((3, 3))

A2 = A1.copy()
A2 = A2.astype('bool')  # conversion into bool type

A3_idx = A2.copy()      # creating matrix for index reference
A3_idx[0, 2] = True
A3_idx[1][0] = True
A3_idx[2] = True

X1 = np.array([[0, 0, 0],
              [0, 0, 8],
              [0, 1, 2]])
X1[A3_idx] = 300 # broadcasting using fully sized matrix as index reference 

# Conditioned filtering
X2 = X1.copy()
zeros_idx = X2 == 0     # get all 0 values
X2[zeros_idx] = 10	    # set them to 10

# NumPy arrays contain only one type of variables. If there are more, it will be converted into string.
# If there are numbers and there’s also bool value, it’s going to be changed into a number. 
# Conversion priorities: string > int > bool
X_dtype = X.dtype

In [ ]:
print("A1:\n", A1); print("A2:\n", A2); print("A3_idx:\n", A3_idx)
print("X1:\n", X1); print("X2:\n", X2); print("X_dtype =", X_dtype)

In [5]:
# Stacking
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])
v_stack = np.vstack((a1, a2))	# joins arrays vertically, with a1 on the top
h_stack = np.hstack((a1, a2))	# joins arrays horizontally, with a1 on the left

3.1622776601683795

In [ ]:
# TODO
# hsplit - splits an array into several smaller arrays


# Solving linear systems
A = np.array([[-1, 3],
              [3, 2]])
b = np.array([7, 1])
x = np.linalg.solve(A, b)	# [-1. 2.]
d = np.linalg.det(A)	    # -11
b_norm = np.linalg.norm(b)
# Eigen Vectors..!