In [8]:
# Import NumPy package to load its functions (np is conventional abbreviation to use in the code)
import numpy as np

In [9]:
# Initializing NumPy arrays with lists
a = np.array([1, 2, 3, 4])		# (1D) vector array (lowercase name)
A = np.array([[2, 3],   		# (2D) matrix array (uppercase name)
              [4, 5]])

# Initializing NumPy arrays with numbers
b = np.arange(5)		        # vector from 0 to 4
c = np.arange(10, 15)	        # vector from 10 to 14
d = np.arange(15, 50, 10)	    # vector from 15 to 49, with steps of 10
e = np.linspace(0, 100, 5)	    # vector 5 number values between 0 and 100
f = np.empty(2)		            # vector declaration that needs to be initialized
B = np.zeros((2, 3, 4))	        # matrix 2x3x4 (3D) matrix with zeros
C = np.ones((1, 2))		        # matrix 1x2 (2D) matrix with ones
X = np.random.rand(5, 5)	    # matrix 5x5 (2D) with random values <0, 1)
Y = np.random.randn(100, 36, 36)# matrix 50x36x36 (3D) with random numbers from normal distribution

In [ ]:
print("a =", a); print("A:\n", A); print("b =", b); print("c =", c); print("d =", d); print("e =", e); 
print("f =", f); print("B:\n", B); print("C:\n", C); print("X:\n", X); print("Y:\n", Y)

In [11]:
# Displaying properties of NumPy arrays (shape, ndim, size)
B = np.zeros((2, 3, 4))
B_shape = B.shape   # length of each dimensions - shape of array
B_ndim = B.ndim    	# amount of array dimensions
B_size = B.size    	# amount of values in array

In [ ]:
print("B_shape =", B_shape); print("B_ndim =", B_ndim); print("B_size =", B_size)

In [13]:
# Transforming functions of NumPy arrays (transpose, reshape)
Y = np.random.randn(2, 2, 3)
Y_transposed = np.transpose(Y)          # transposes Y - reverses the axes of an array
Y_transposed = Y.transpose()            # does the same, without having to access np
Y_reshaped = np.reshape(Y, (2, 2 * 3))  # reshapes dimensions from 2x3x2 matrix to 2x6 
Y_reshaped = Y.reshape(2, 2 * 3)        # does the same, without having to access np
Y_reshaped = Y.reshape(-1, 2 * 3)       # does the same, -1 lets NumPy calculate the shape length based on the remaining number of elements

In [14]:
print("Y.shape =", Y.shape); print("Y:\n", Y); print("Y_transposed.shape", Y_transposed.shape); print("Y_transposed:\n", Y_transposed); 
print("Y_reshaped.shape", Y_reshaped.shape); print("Y_reshaped:\n", Y_reshaped)

Y.shape = (2, 2, 3)
Y:
 [[[ 0.11309797  1.09882021  0.91810204]
  [-1.94165384  0.18165287 -0.2054063 ]]

 [[-1.14929263  0.07298979 -0.79721415]
  [ 3.01078996 -1.27060386 -1.03670608]]]
Y_transposed.shape (3, 2, 2)
Y_transposed:
 [[[ 0.11309797 -1.14929263]
  [-1.94165384  3.01078996]]

 [[ 1.09882021  0.07298979]
  [ 0.18165287 -1.27060386]]

 [[ 0.91810204 -0.79721415]
  [-0.2054063  -1.03670608]]]
Y_reshaped.shape (2, 6)
Y_reshaped:
 [[ 0.11309797  1.09882021  0.91810204 -1.94165384  0.18165287 -0.2054063 ]
 [-1.14929263  0.07298979 -0.79721415  3.01078996 -1.27060386 -1.03670608]]


In [15]:
# Computing functions over axises in NumPy arrays (sum/mean/exp etc.)
X = np.array([[1, 3, 5, 7],
              [6, 7, 3, 1],
              [1, 4, 5, 1]])
X_sum = np.sum(X, axis=0)	    # sum out of elements inside of 1. array: (1,6,1)(3,7,4)(5,3,5)(7,1,1) [columns]

Z = np.array([[[2, 4, 6],
               [1, 2, 3]],

              [[4, 6, 8],
               [7, 8, 9]]])
Z_mean_0 = np.mean(Z, axis=0)	# compute means out of elements inside of 1. array - 1. row uses: (2,4)(4,6)(6,8)  [1on1 outside]
Z_mean_1 = np.mean(Z, axis=1)	# compute means out of elements inside of 2. array - 1. row uses: (2,1)(4,2),(6,3) [columns]
Z_mean_2 = Z.mean(axis=2)	    # compute means out of elements inside of 3. array - 1. row uses: (2,4,6)(1,2,3)   [rows]

In [16]:
print("X_sum", X_sum); print("Z_mean_0:\n", Z_mean_0)
print("Z_mean_1:\n", Z_mean_1); print("Z_mean_2:\n", Z_mean_2)

X_sum [ 8 14 13  9]
Z_mean_0:
 [[3. 5. 7.]
 [4. 5. 6.]]
Z_mean_1:
 [[1.5 3.  4.5]
 [5.5 7.  8.5]]
Z_mean_2:
 [[4. 2.]
 [6. 8.]]


In [ ]:
# Arithmetic element wise operations with vectors
a1 = np.array([9, 8, 7, 6])
a2 = np.array([1, 2, 3, 4])
a_added = a1 + a2   # adding (np.add - has more parameters for adding)
a_subtr = a1 - a2   # subtracting (np.subtract)
a_multi = a1 * a2   # multiplication (np.multiply)
a_divid = a1 / a2   # division (np.divide)

# Vectorization with np. vs Python loops)
# ELEMENT WISE MULTIPLICATION
a_multi = np.multiply(a1,a2)    # [9*1, 8*2, 7*3, 8*4]
a_multi = np.zeros(len(a1))
for i in range(len(a1)):
    a_multi[i] = a1[i] * a2[i]

# DOT PRODUCT
a_dot = np.dot(a1,a2)	        # 9*1 + 8*2 + 7*3 + 6*4
a_dot = 0
for i in range(len(a1)):
    a_dot += a1[i] * a2[i]

# OUTER PRODUCT
a_outer = np.outer(a1,a2)	    # [[9*1, 9*2, 9*3, 9*4], [8*1, 8*2 …], … ]
a_outer = np.zeros((len(a1),len(a2)))
for i in range(len(a1)):
    for j in range(len(a2)):
        a_outer[i,j] = a1[i] * a2[j]

In [ ]:
print("a_added =", a_added); print("a_subtr =", a_subtr); print("a_multi =", a_multi); print("a_divid =", a_divid);
print("a_multi =", a_multi); print("a_dot =", a_dot); print("a_outer:\n", a_outer)